### ISSUE TITLE
Does not compile with g++ 6.2

### ISSUE THREAD

**Issue by morrisonlevi** [wardw/array_view#1]
There are two issues:

1. `ptrdiff_t` should be `std::ptrdiff_t` or `using std::ptrdiff_t` should be used.
2. When defining `bounds_type` in `array_view` and `strided_array_view` I believe you need to specify `av::bounds<Rank>` because you also define a member function `bounds` and the compiler doesn't work it out correctly.

**Comment by wardw** [comment]
Thanks for this. Right on both counts.
