### ISSUE TITLE
License header with attributions

### ISSUE THREAD

**Issue by fish2000** [wardw/array_view#2]
Hi, thanks for implementing this. I added it to a project of mine and thought, upon doing so, that it could use a license header with attributions (which I pulled those out of the README). This is here:

https://github.com/fish2000/libimread/blob/9e826ef29a4f315a3d58743798a54702c6be5956/include/libimread/ext/arrayview.hh

… if it’s to your liking (or disliking) in any way do let me know. Thanks again for `array_view`, yes!

**Comment by wardw** [comment]
Thanks for this. I took yours as a template and added a slightly abridged version.  Yes, good to have the header properly self-contained. Much better. Thanks for the nod!
